name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry  # Ensure poetry is installed correctly
      - name: Navigate to tiny-database directory
        run: |
             cd ./tiny-database
             poetry install

      - name: Test with pytest and coverage
        run: |
          pytest --cov=. --cov-fail-under=100
